CodeFirst/Controllers/HomeController.cs
using CodeFirst.Models;
using CodeFirst.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace CodeFirst.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        ApplicationDbContext dbContext = new ApplicationDbContext();
        List<Subscriber> Slists = new List<Subscriber>();
        List<int?> listIDs = new List<int?>();
        List<M_Campaigns> campaigns = new List<M_Campaigns>();
        int cnt,cnt1;
        public ActionResult Index()
        {
            string uid = User.Identity.GetUserId();
            DashboardViewModel model = new DashboardViewModel();
            listIDs = dbContext.UsersList.Where(u => u.UsersID == uid).Select(l => l.ListID).ToList();
            foreach (var item in listIDs)
            {
                
                cnt += dbContext.Subscribers.Where(l => l.ListID == item && l.Unsubscribe==false).Count();
                cnt1 += dbContext.Subscribers.Where(l => l.ListID == item && l.Unsubscribe == true).Count();
            }
            model.NoOfLists = dbContext.UsersList.Where(u => u.UsersID == uid).Count();
            model.NoOfSubscribers = cnt;
            model.NoOfUnSubscribers = cnt1;
            model.NoOfCampaigns = dbContext.UsersCampaigns.Where(u => u.UsersID == uid).Count();
            return View(model);
           // return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CodeFirst/Controllers/ListController.cs
using CodeFirst.Models;
using CodeFirst.ViewModels;
using Excel;
using LumenWorks.Framework.IO.Csv;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using Excel.Log;

namespace CodeFirst.Controllers
{

    public class ListController : Controller
    {
        NewList list = null;
        Subscriber subscribers = new Subscriber();
        List<int?> listIds = new List<int?>();
        ListViewModel LVmodel = new ListViewModel();
        string userID = null;
        public string GetUser()
        {
            userID = User.Identity.GetUserId();
            return userID;
        }
        // GET: List
        [Authorize]
        public ActionResult Index()
        {
            list = new NewList();
            LVmodel = new ListViewModel();
            userID = GetUser();
           
            try
            {
                LVmodel = list.ViewList(userID);
            }
            catch (CustomSqlException ex)
            {
                ModelState.AddModelError("listindex", ex.message);
                return View();
            }

            return View(LVmodel);
        }
               
        [Authorize]
        [HttpGet]
        public ActionResult NewList()
        {
            ViewBag.country = new SelectList(Country.GetCountries(), "CountryId", "CountryName");
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult NewList(NewList model)
        {

            if (ModelState.IsValid)
            {
                string UsersID = User.Identity.GetUserId();
                List<string> ListNames = new List<string>();
                string success = null;
                if (model != null)
                {
                    try
                    {
                        success=model.SaveList(UsersID);
                        if (success != "Saved")
                        {
                            ModelState.AddModelError("Errorlistname", success);
                            ViewBag.country = new SelectList(Country.GetCountries(), "CountryId", "CountryName");
                            return View();
                        }
                    }
                    catch (CustomSqlException ex)
                    {
                        if (ex.ErrorCode == 100)
                        {
                            ModelState.AddModelError("error", ex.message);
                            return RedirectToAction("NewList");
                        }
                        else if (ex.ErrorCode == 101)
                        {
                            ModelState.AddModelError("Error", "logical exception");
                            return RedirectToAction("NewList");
                        }
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("error", "Errr occured in business logic");
                        return RedirectToAction("NewList");
                    }
                   
                }
                else {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            return RedirectToAction("Index");
        }
       
        [Authorize]
        public FilePathResult SampleExcel(string fileName)
        {
            return new FilePathResult(@"~\ExcelFiles\" + fileName + ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }
        [Authorize]
        public FileContentResult SampleCSV(string fileName)
        {
            //return new FilePathResult(@"~\CSVFiles\" + fileName + ".csv", "text/csv");
            var path = "FirstName, LastName, EmailAddress, AlternateEmailAddress, Address, Country, City";
            return File(new System.Text.UTF8Encoding().GetBytes(path), "text/csv", "SampleCSV.csv");
        }
        [Authorize]
        public ActionResult EditList(int? id)
        {
            ViewBag.country = new SelectList(Country.GetCountries(), "CountryId", "CountryName");
            NewList model = new NewList();
            try
            {
                model = model.EditList(id);
            }
            catch (CustomSqlException ex)
            {
                if (ex.ErrorCode == 100)
                {
                    ModelState.AddModelError("error", ex.message);
                    return RedirectToAction("EditList");
                }
                else if (ex.ErrorCode == 101)
                {
                    ModelState.AddModelError("Error", "logical exception");
                    return RedirectToAction("EditList");
                }
            }
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public ActionResult EditList(NewList model)
        {
            bool result;
            try
            {
                result = model.UpdateList();
                return RedirectToAction("Index");
            }
            catch (CustomSqlException ex)
            {
                ModelState.AddModelError("upadateList", ex.message);
                return RedirectToAction("EditList");
            }
        }

        [AllowAnonymous]
        public ActionResult UnSubscribe(int? SubscriberID)
        {
            Subscriber model = new Subscriber();
            bool res;
            if (SubscriberID != null)
            {
                try
                {
                    res = model.Unsub(SubscriberID);
                    if (res)
                    {
                        return JavaScript("window.close();");
                    }
                }
                catch (CustomSqlException ex)
                {
                    ModelState.AddModelError("Unsub", ex.message);
                }
            }
            return JavaScript("window.close()");

        }

    }
}

CodeFirst/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CodeFirst/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CodeFirst/Views/Home/Index.cshtml
@model CodeFirst.ViewModels.DashboardViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

</head>
<body>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Dashboard</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        @if (Model != null)
        {
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">@Model.NoOfLists</div>
                                    <div>Total Number Of Lists</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">@Html.ActionLink("View Details", "Index", "List")</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="glyphicon glyphicon-user"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">@Model.NoOfSubscribers</div>
                                    <div>Number Of Subscribers</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">
                                    @Html.ActionLink("View Details", "ViewSubscribers", "Subscriber")
                                </span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">@Model.NoOfCampaigns</div>
                                    <div>Number Of Campaigns</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">
                                    @Html.ActionLink("View Details", "Campaign", "Campaign")
                                </span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">@Model.NoOfUnSubscribers</div>
                                <div>Number Of UnSubscribers</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">
                                    @Html.ActionLink("View Details", "Unsubscribers", "List")
                                </span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        }


</body>
</html>